name: Deploy site

on:
  workflow_run:
    workflows: ["Build demo site"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name abbdemotaskstorage --auth-mode key -d '$web' -s .
.
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
